<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEL0bmef\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEL0bmef/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEL0bmef.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEL0bmef\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEL0bmef\App_KernelDevDebugContainer([
    'container.build_hash' => 'EL0bmef',
    'container.build_id' => 'dae4dd12',
    'container.build_time' => 1649952843,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEL0bmef');
